'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class Configuraciones
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Configuraciones = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Configuraciones()),Configuraciones)
    
    Public Shared ReadOnly Property [Default]() As Configuraciones
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MostrarPanelRapido() As Boolean
        Get
            Return CType(Me("MostrarPanelRapido"),Boolean)
        End Get
        Set
            Me("MostrarPanelRapido") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Enviar_x_Correo() As Boolean
        Get
            Return CType(Me("Enviar_x_Correo"),Boolean)
        End Get
        Set
            Me("Enviar_x_Correo") = value
        End Set
    End Property
End Class
