'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Destetes_Completos_o_Parciales
    Public Property Id As Integer
    Public Property Lote_Engorde As String
    Public Property Lote_Gestacion As String
    Public Property Documento As String
    Public Property Fecha As Nullable(Of Date)
    Public Property No_Cerditos As Nullable(Of Integer)
    Public Property No_Cerdas As Nullable(Of Integer)
    Public Property Tota_Peso As Nullable(Of Decimal)

End Class
