'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fecha_Dias_Desarrollo
    Public Property ID As Integer
    Public Property Lote_No As String
    Public Property Fecha As Date
    Public Property Dias As Integer
    Public Property Fecha_Semanal As Nullable(Of Date)

End Class
