'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GRANJAEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GRANJAEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property v_consulta_reemplazos() As DbSet(Of v_consulta_reemplazos)
    Public Overridable Property Registo_Celo() As DbSet(Of Registo_Celo)
    Public Overridable Property ClasesHatosReprod() As DbSet(Of ClasesHatosReprod)
    Public Overridable Property Configuraciones_Globales() As DbSet(Of Configuraciones_Globales)
    Public Overridable Property Movimientos_Lotes_Int() As DbSet(Of Movimientos_Lotes_Int)
    Public Overridable Property Destetes_Completos_o_Parciales() As DbSet(Of Destetes_Completos_o_Parciales)
    Public Overridable Property Fecha_Dias_Desarrollo() As DbSet(Of Fecha_Dias_Desarrollo)
    Public Overridable Property MotivosDefuncionAntesDestete() As DbSet(Of MotivosDefuncionAntesDestete)
    Public Overridable Property vReporteSalidasFarmacosXEtapa() As DbSet(Of vReporteSalidasFarmacosXEtapa)

End Class
