'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Movimientos_Lotes_Int
    Public Property ID_Movimiento As Integer
    Public Property De_Lote As String
    Public Property A_Lote As String
    Public Property Fecha_Movimiento As Date
    Public Property Motivo As String
    Public Property Cantidad As Integer
    Public Property Usuario_Creador As String
    Public Property Costo As Double
    Public Property Documento_NO As String

End Class
