'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Registo_Celo
    Public Property ID_Celo As Integer
    Public Property Codigo_Cerda As String
    Public Property Tipo_Cerda As String
    Public Property Evento As String
    Public Property Fecha_Hora_Creacion As Date
    Public Property Fecha As Date
    Public Property Hora As System.TimeSpan
    Public Property Peso As Decimal
    Public Property Orden As Integer
    Public Property Observaciones As String
    Public Property Etapa As String
    Public Property EdadDias As Nullable(Of Integer)
    Public Property IdClase As String

End Class
