'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_consulta_reemplazos
    Public Property id As Nullable(Of Long)
    Public Property IdCerda As String
    Public Property Fecha_Nacimiento As Date
    Public Property L_Genetica As String
    Public Property Padre As String
    Public Property Madre As String
    Public Property etapa As String
    Public Property Tipo As String
    Public Property edaddias As Nullable(Of Integer)
    Public Property IdClase As String

End Class
