'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vReporteSalidasFarmacosXEtapa
    Public Property SalidaNo As Long
    Public Property Fecha As Date
    Public Property Codigo As String
    Public Property Descripcion As String
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Etapa As String
    Public Property Bodega As String
    Public Property idBodega As String

End Class
